### ISSUE TITLE
No tracing GC?

### ISSUE THREAD

**Issue by olleharstedt** [jpdeplaix/cervoise#1]
Hi!

One year ago you said this on OCaml IRC:

> 16:26 <jpdeplaix> artagnon: I'm currently doing a copying GC with llvm 

Are you referring to this repository? But now you use a conservative GC instead? I'm asking because I'm trying to use LLVM with OCaml GC, and am looking for information.

Regards
Olle

**Comment by jpdeplaix** [comment]
Yep I was referring to this repository. I was always using a conservative GC (boehem GC) and one year ago I tried to change it to a proper custom copying GC but I got bored of trying (plus it was taking too much time) so I just momentarily stopped. I'll maybe try again later but it's not a priority anymore.

**Comment by jpdeplaix** [comment]
All my work is in the branch real-gc. I've something else on my machine but it doesn't compile

**Comment by olleharstedt** [comment]
Ah, OK. Thank you, I might check it out for ideas. Bye!
